export enum RESTAURANT_ACTION_TYPES {
   FETCH_RESTAURANT_START = 'restaurant/FETCH_RESTAURANT_START',
   FETCH_RESTAURANT_SUCCESS = 'restaurant/FETCH_RESTAURANT_SUCCESS',
   FETCH_RESTAURANT_FAILED = 'restaurant/FETCH_RESTAURANT_FAILED',
};

export enum RESTAURANT_BYID_ACTION_TYPES {
   FETCH_RESTAURANT_BYID_START = 'restaurant/FETCH_RESTAURANT_BYID_START',
   FETCH_RESTAURANT_BYID_SUCCESS = 'restaurant/FETCH_RESTAURANT_BYID_SUCCESS',
   FETCH_RESTAURANT_BYID_FAILED = 'restaurant/FETCH_RESTAURANT_BYID_FAILED',
}