export enum RECIPES_RATINGS_ACTION_TYPES {
   FETCH_RECIPES_RATINGS_START = 'rating/FETCH_RECIPES_RATINGS_START',
   FETCH_RECIPES_RATINGS_SUCCESS = 'rating/FETCH_RECIPES_RATINGS_SUCCESS',
   FETCH_RECIPES_RATINGS_FAILED = 'rating/FETCH_RECIPES_RATINGS_FAILED',
}

export enum RESTAURANTS_RATINGS_ACTION_TYPES {
   FETCH_RESTAURANTS_RATINGS_START = 'rating/FETCH_RESTAURANTS_RATINGS_START',
   FETCH_RESTAURANTS_RATINGS_SUCCESS = 'rating/FETCH_RESTAURANTS_RATINGS_SUCCESS',
   FETCH_RESTAURANTS_RATINGS_FAILED = 'rating/FETCH_RESTAURANTS_RATINGS_FAILED',
}

export enum SINGLE_RATING_ACTION_TYPES {
   FETCH_SINGLE_RATING_START = 'rating/FETCH_SINGLE_RATING_START',
   FETCH_SINGLE_RATING_SUCCESS = 'rating/FETCH_SINGLE_RATING_SUCCESS',
   FETCH_SINGLE_RATING_FAILED = 'rating/FETCH_SINGLE_RATING_FAILED',
}

export enum ADD_RATING_ACTION_TYPES {
   ADD_RATING_START = 'rating/ADD_RATING_START',
   ADD_RATING_SUCCESS = 'rating/ADD_RATING_SUCCESS',
   ADD_RATING_FAILED = 'rating/ADD_RATING_FAILED',
}

export enum REMOVE_RATING_ACTION_TYPES {
   REMOVE_RATING_START = 'rating/REMOVE_RATING_START',
   REMOVE_RATING_SUCCESS = 'rating/REMOVE_RATING_SUCCESS',
   REMOVE_RATING_FAILED = 'rating/REMOVE_RATING_FAILED',
}